// window.questions = {
//     genre: {
//         options: ['m', 'f']
//     },
//     age: {},
//     degree: {
//         options: ['Não estudou', 'Fundamental', 'Médio', 'Superior']
//     },
//     spendDisposition: {}, // 20 a 39 40 a 59 60 a 79 80 a 99 Mais de 100
//     where: {
//         options: [
//             'Um restaurante, no jantar',
//             'Um restaurante, no almoço',
//             'Um bar, à noite',
//             'Uma chácara, durante o dia',
//         ]
//     },
//     preferredFood: {
//         options: [
//             'Massa',
//             'Regional',
//             'Fast Food', // 2
//             'Carne',
//             'Self Service',// 4
//         ]
//     },
//     preferredMusic: {
//         options: [
//             'Ambiente',
//             'Eletrônica',
//             'Samba',
//             'MPB', //3
//             'Forró',
//             'Sertanejo',
//             'Rock',
//             'Todos os ritmos', //7
//         ]
//     },
//     likeDance: {
//         options: ['yes', 'no']
//     }
// };

window.respondents = [
    {
        genre: 0,
        age: 39,
        degree: 3,
        spendDisposition: 10,
        where: 3,
        preferredFood: 1,
        preferredMusic: 4,
        likeDance: 0,
    },
    {
        genre: 1,
        age: 25,
        degree: 3,
        spendDisposition: 60,
        where: 2,
        preferredFood: 1,
        preferredMusic: 1,
        likeDance: 1,
    },
    {
        genre: 0,
        age: 24,
        degree: 3,
        spendDisposition: 10,
        where: 0,
        preferredFood: 0,
        preferredMusic: 5,
        likeDance: 1,
    },
    {
        genre: 0,
        age: 42,
        degree: 2,
        spendDisposition: 40,
        where: 3,
        preferredFood: 3,
        preferredMusic: 7,
        likeDance: 1,
    },
    {
        genre: 0,
        age: 46,
        degree: 3,
        spendDisposition: 150,
        where: 0,
        preferredFood: 3,
        preferredMusic: 2,
        likeDance: 1,
    },
    {
        genre: 0,
        age: 38,
        degree: 3,
        spendDisposition: 90,
        where: 3,
        preferredFood: 4,
        preferredMusic: 6,
        likeDance: 1,
    },
    {
        genre: 1,
        age: 26,
        degree: 2,
        spendDisposition: 20,
        where: 2,
        preferredFood: 4,
        preferredMusic: 1,
        likeDance: 1,
    },
    {
        genre: 1,
        age: 21,
        degree: 2,
        spendDisposition: 50,
        where: 1,
        preferredFood: 0,
        preferredMusic: 3,
        likeDance: 1,
    },
    {
        genre: 1,
        age: 37,
        degree: 3,
        spendDisposition: 120,
        where: 3,
        preferredFood: 0,
        preferredMusic: 0,
        likeDance: 1,
    },
    {
        genre: 1,
        age: 31,
        degree: 2,
        spendDisposition: 80,
        where: 3,
        preferredFood: 4,
        preferredMusic: 7,
        likeDance: 0,
    },
    {
        genre: 1,
        age: 33,
        degree: 3,
        spendDisposition: 70,
        where: 3,
        preferredFood: 4,
        preferredMusic: 3,
        likeDance: 1,
    },
    {
        genre: 1,
        age: 23,
        degree: 2,
        spendDisposition: 20,
        where: 2,
        preferredFood: 0,
        preferredMusic: 6,
        likeDance: 1,
    },
    {
        genre: 1,
        age: 20,
        degree: 2,
        spendDisposition: 20,
        where: 0,
        preferredFood: 4,
        preferredMusic: 7,
        likeDance: 1,
    },
    {
        genre: 0,
        age: 29,
        degree: 2,
        spendDisposition: 30,
        where: 2,
        preferredFood: 3,
        preferredMusic: 6,
        likeDance: 1,
    },
    {
        genre: 0,
        age: 19,
        degree: 2,
        spendDisposition: 20,
        where: 1,
        preferredFood: 4,
        preferredMusic: 1,
        likeDance: 1,
    },
    {
        genre: 0,
        age: 24,
        degree: 3,
        spendDisposition: 30,
        where: 1,
        preferredFood: 4,
        preferredMusic: 2,
        likeDance: 1,
    },
    {
        genre: 0,
        age: 34,
        degree: 3,
        spendDisposition: 90,
        where: 3,
        preferredFood: 4,
        preferredMusic: 7,
        likeDance: 1,
    },
    {
        genre: 0,
        age: 38,
        degree: 3,
        spendDisposition: 150,
        where: 3,
        preferredFood: 4,
        preferredMusic: 7,
        likeDance: 1,
    },
    {
        genre: 0,
        age: 39,
        degree: 3,
        spendDisposition: 150,
        where: 1,
        preferredFood: 3,
        preferredMusic: 6,
        likeDance: 1,
    },
    {
        genre: 0,
        age: 30,
        degree: 3,
        spendDisposition: 50,
        where: 3,
        preferredFood: 4,
        preferredMusic: 4,
        likeDance: 1,
    },
];